### PR TITLE
White Space and Linter

### PR DESCRIPTION
**Pull request by samrocksc**
This PR addresses the need for a pull request also a linter of any kind to assist in finding errors in the project moving forward.  It addresses issue #86

### CODE REVIEW

**Comment by samrocksc** [comment]
@monteslu this one is almost ready to go, gonna make a few touch ups and tests before i release this one especially on the math nodes

**Comment by samrocksc** [comment]
@monteslu @louiemontes you can also test this at https://shoutinginfrench.com:3000 if you think there there are any critical errors that might be caused from removal of whitespace.

**Comment by warbrett** [comment]
Why remove the test folder from the linter? 

It's pretty normal to lint against that just because linting helps with things like unused variables, etc.

**Comment by samrocksc** [comment]
@warbrett The main reason i left the test folder left out was because it required about 4000 lines of whitespace change, and also it is no longer effective, and is going to require a complete reqork.  

The node-red method of API access was to use ajax requests, while we are using a modified red.comms core, these 2 are very incompatible at this point in evolution.  In the next PR I'm going to be working on i will be removing and hopefully implementing tests again.

**Comment by samrocksc** [comment]
@monteslu yo, i think i got this one.  i tested it for about an hour :P.

**Comment by monteslu** [comment]
@samrocksc add eslint to dev deps

**Comment by samrocksc** [comment]
What do you mean by dev ops?

**Comment by samrocksc** [comment]
@monteslu added eslint babel-eslint to save-dev, we should be good.  It's also going to automatically use the local eslint.

**Pull request merged**
